version: "2"
services:
  # codewind-file-watcher:
  #   environment:
  #     - APPMETRICS=true
  #     - LD_LIBRARY_PATH=/server/node_modules/appmetrics/
  #   ports:
  #     - "127.0.0.1:3002:3001"
  #     - "127.0.0.1:9091:9091"
  #     - "127.0.0.1:9222:9222"
  #   entrypoint: /scripts/root-watcher.sh ${WORKSPACE_DIRECTORY}

  codewind-pfe:
    environment:
      - APPMETRICS=true
      - LD_LIBRARY_PATH=/node_modules/appmetrics/
      - EXTRA_GIT_OPTION=-f /codewind-workspace/.config/git.config help.autoCorrect 1
    ports:
      - "127.0.0.1:3001:3001"
    command: [sh, -c, "npm install && npm run coverage"]
